TYPE = EXECUTABLE
NAME = alloy_examples
rwildcard=$(foreach d,$(wildcard $1*),$(call rwildcard,$d/,$2) $(filter $(subst *,%,$2),$d))
CXXFILES += $(patsubst %.cpp,%,$(call rwildcard,src/example/,*.cpp))
LIBS = Alloy
IMPORTLIBS += glfw cereal
GCCFFLAGS = -fopenmp
DEFINES += -DNO_EXC_MATH
DATAFILES = $(call rwildcard,assets/,*.ttf) 
DATAFILES+=$(call rwildcard,assets/,*.png) 
DATAFILES+=$(call rwildcard,assets/,*.vs) 
DATAFILES+=$(call rwildcard,assets/,*.fs) 
DATAFILES+=$(call rwildcard,assets/,*.ply) 
DATAFILES+=$(call rwildcard,assets/,*.obj) 
DATAFILES+=$(call rwildcard,assets/,*.mtl) 
DATAFILES+=$(call rwildcard,assets/,*.jpg)
IPATHSUFFIX = ./include/core/ ./include/example/
LPATHSUFFIX = $(PREBUILT_ROOT)/dso
include $(SRC_ROOT)/build/Makefile.master
